-- MySQL Script generated by MySQL Workbench
-- Ср 16 сен 2020 16:41:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_role` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_avatar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_avatar` (
  `id` INT NOT NULL,
  `file_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`city` (
  `id` INT NOT NULL,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(100) NOT NULL,
  `summary` TEXT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `role_id` INT NOT NULL,
  `avatar_id` INT NOT NULL,
  `city_id` INT NOT NULL,
  `birthday` DATE NULL,
  `rating` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_user_role1_idx` (`role_id` ASC) VISIBLE,
  INDEX `fk_user_user_avatar1_idx` (`avatar_id` ASC) VISIBLE,
  INDEX `fk_user_city1_idx` (`city_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_user_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `mydb`.`user_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_user_avatar1`
    FOREIGN KEY (`avatar_id`)
    REFERENCES `mydb`.`user_avatar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `mydb`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(60) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `address` VARCHAR(255) NULL,
  `price` INT NULL,
  `execution` DATE NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `user_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_task_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Таблица для хранения заданий.\n';


-- -----------------------------------------------------
-- Table `mydb`.`user_contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_contacts` (
  `id` INT NOT NULL,
  `phone` VARCHAR(45) NULL,
  `skype` VARCHAR(45) NULL,
  `messager` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_contacts_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_contacts_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_favorites` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_favorite_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_favorites_user1_idx` (`user_id` ASC, `user_favorite_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_favorites_user1`
    FOREIGN KEY (`user_id` , `user_favorite_id`)
    REFERENCES `mydb`.`user` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_favorites`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_favorites` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_favorite_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_favorites_user1_idx` (`user_id` ASC, `user_favorite_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_favorites_user1`
    FOREIGN KEY (`user_id` , `user_favorite_id`)
    REFERENCES `mydb`.`user` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`chat_messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`chat_messages` (
  `id` INT NOT NULL,
  `text` VARCHAR(400) NULL,
  `created_at` TIMESTAMP NULL,
  `sender_id` INT NOT NULL,
  `recipient_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_chat_messages_user1_idx` (`sender_id` ASC, `recipient_id` ASC) VISIBLE,
  CONSTRAINT `fk_chat_messages_user1`
    FOREIGN KEY (`sender_id` , `recipient_id`)
    REFERENCES `mydb`.`user` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_site_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_site_settings` (
  `id` INT NOT NULL,
  `show_customers` TINYINT NULL,
  `hide_profile` TINYINT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_site_settings_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_site_settings_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_notification_settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_notification_settings` (
  `user_id` INT NOT NULL,
  `new_messages` TINYINT NULL,
  `task_actions` TINYINT NULL,
  `new_responds` TINYINT NULL,
  INDEX `fk_user_notification_settings_user1_idx` (`user_id` ASC) VISIBLE,
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_notification_settings_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`task_respond`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`task_respond` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `comment` TEXT NULL,
  `price` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_respond_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_task_respond_task1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_respond_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_task_respond_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `mydb`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`task_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`task_file` (
  `id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `file_path` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_task_file_task1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_task_file_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `mydb`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_categoryes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_categoryes` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_categoryes_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_user_categoryes_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_categoryes_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_categoryes_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_review` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `user_reviewer_id` INT NOT NULL,
  `task_id` INT NOT NULL,
  `comment` VARCHAR(45) NULL,
  `rating` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_review_user1_idx` (`user_id` ASC, `user_reviewer_id` ASC) VISIBLE,
  INDEX `fk_user_review_task1_idx` (`task_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_review_user1`
    FOREIGN KEY (`user_id` , `user_reviewer_id`)
    REFERENCES `mydb`.`user` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_review_task1`
    FOREIGN KEY (`task_id`)
    REFERENCES `mydb`.`task` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
